### ISSUE TITLE
equality?

### ISSUE THREAD

**Issue by pmetzger** [mirage/ocaml-diet#7]
I note that the package seems to lack an equality test for interval sets. Would that be a feasible addition?

**Comment by NathanReb** [comment]
I'm currently looking into it, it's definitely feasible using `fold`. Being able to write an actual equal function that wouldn't have to allocate a list for each set would be nice but I'm not sure yet whether the representation are canonical or not.

**Comment by NathanReb** [comment]
Actually that shouldn't even matter.
